from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(257, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(0, 310, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn0.setObjectName("btn0")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(200, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.box = QtWidgets.QCheckBox(self.centralwidget)
        self.box.setGeometry(QtCore.QRect(200, 80, 51, 21))
        self.box.setObjectName("box")
        self.topic = QtWidgets.QLabel(self.centralwidget)
        self.topic.setGeometry(QtCore.QRect(0, 0, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.topic.setFont(font)
        self.topic.setStyleSheet("background-color: rgb(142, 240, 255);\n" "color: rgb(0, 0, 0);")
        self.topic.setObjectName("topic")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(0, 50, 191, 51))
        self.result.setStyleSheet("background-color: rgb(85, 170, 0);\n" "color: rgb(255, 255, 255);")
        self.result.setObjectName("result")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(60, 170, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn5.setObjectName("btn5")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(60, 100, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(130, 100, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn9.setObjectName("btn9")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(0, 100, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn7.setObjectName("btn7")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(0, 170, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn4.setObjectName("btn4")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(130, 170, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn6.setObjectName("btn6")
        self.btnresult = QtWidgets.QPushButton(self.centralwidget)
        self.btnresult.setGeometry(QtCore.QRect(120, 310, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnresult.setFont(font)
        self.btnresult.setStyleSheet("background-color: rgb(255, 83, 86);\n" "color: rgb(0, 0, 0);")
        self.btnresult.setObjectName("btnresult")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(130, 240, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn3.setObjectName("btn3")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(60, 240, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(0, 240, 61, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btn1.setObjectName("btn1")
        self.btnplus = QtWidgets.QPushButton(self.centralwidget)
        self.btnplus.setGeometry(QtCore.QRect(190, 100, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnplus.setFont(font)
        self.btnplus.setStyleSheet("background-color: rgb(255, 170, 0);\n" "color: rgb(0, 0, 0);")
        self.btnplus.setObjectName("btnplus")
        self.btnminus = QtWidgets.QPushButton(self.centralwidget)
        self.btnminus.setGeometry(QtCore.QRect(190, 170, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnminus.setFont(font)
        self.btnminus.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(255, 170, 0);")
        self.btnminus.setObjectName("btnminus")
        self.btnmultiply = QtWidgets.QPushButton(self.centralwidget)
        self.btnmultiply.setGeometry(QtCore.QRect(190, 240, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnmultiply.setFont(font)
        self.btnmultiply.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(255, 170, 0);")
        self.btnmultiply.setObjectName("btnmultiply")
        self.btndivide = QtWidgets.QPushButton(self.centralwidget)
        self.btndivide.setGeometry(QtCore.QRect(190, 310, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btndivide.setFont(font)
        self.btndivide.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(255, 170, 0);")
        self.btndivide.setObjectName("btndivide")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.radioButton.setText(_translate("MainWindow", "Func1"))
        self.box.setText(_translate("MainWindow", "Func2"))
        self.topic.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.topic.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.topic.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Калькулятор</p></body></html>"))
        self.result.setText(_translate("MainWindow", "0"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnresult.setText(_translate("MainWindow", "="))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btnplus.setText(_translate("MainWindow", "+"))
        self.btnminus.setText(_translate("MainWindow", "-"))
        self.btnmultiply.setText(_translate("MainWindow", "*"))
        self.btndivide.setText(_translate("MainWindow", "/"))

    def add_functions(self):
        self.btn0.clicked.connect(lambda: self.write_number(self.btn0.text()))
        self.btn1.clicked.connect(lambda: self.write_number(self.btn1.text()))
        self.btn2.clicked.connect(lambda: self.write_number(self.btn2.text()))
        self.btn3.clicked.connect(lambda: self.write_number(self.btn3.text()))
        self.btn4.clicked.connect(lambda: self.write_number(self.btn4.text()))
        self.btn5.clicked.connect(lambda: self.write_number(self.btn5.text()))
        self.btn6.clicked.connect(lambda: self.write_number(self.btn6.text()))
        self.btn7.clicked.connect(lambda: self.write_number(self.btn7.text()))
        self.btn8.clicked.connect(lambda: self.write_number(self.btn8.text()))
        self.btn9.clicked.connect(lambda: self.write_number(self.btn9.text()))
        self.btnplus.clicked.connect(lambda: self.write_number(self.btnplus.text()))
        self.btnminus.clicked.connect(lambda: self.write_number(self.btnminus.text()))
        self.btndivide.clicked.connect(lambda: self.write_number(self.btndivide.text()))
        self.btnmultiply.clicked.connect(lambda: self.write_number(self.btnmultiply.text()))

        self.btnresult.clicked.connect(self.results)

    def write_number(self, number):
        if self.result.text() == "0" or self.is_equal:
            self.result.setText(number)
            self.is_equal = False
        else:
            self.result.setText(self.result.text() + number)

    def results(self):
        res = eval(self.result.text())
        self.result.setText("Результат: " + str(res))
        self.is_equal = True

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
